### ISSUE TITLE
Change a member's nickname

### ISSUE THREAD

**Issue by kzndotsh** [allthingslinux/tux#121]

**Comment by electron271** [comment]
i dont really see the point of this, why not just right click on them?

**Comment by yaboytabby** [comment]
it may have a use case. i'm gonna work on it when i get home.

**Comment by kzndotsh** [comment]
> i dont really see the point of this, why not just right click on them?

Eh it wasn't a major feature, just was going down the list of other bots and was seeing what was easy to knock out. I suppose it would be useful for when someone doesn't want to provide a role with native discord perms so no rush on it or we can back log it for later.

**Comment by electron271** [comment]
change nicknames is a separate discord permission, and to use this command they would need a role in the first place (or modifying the code to add them)

**Comment by FluxC0** [comment]
closing because duplicate and also not needed
