### ISSUE TITLE
Member Count command

### ISSUE THREAD

**Issue by kzndotsh** [allthingslinux/tux#143]

**Comment by doomed-neko** [comment]
isn't that actually provided by the "/info server" command?
https://github.com/allthingslinux/tux/blob/main/tux/cogs/utility/info.py
on line 41

**Comment by kzndotsh** [comment]
> isn't that actually provided by the "/info server" command? https://github.com/allthingslinux/tux/blob/main/tux/cogs/utility/info.py on line 41

Yes I thought so too but it's kind of a large spammy embed so figured it wouldn't hurt to have just one for member count by itself.
