### ISSUE TITLE
Embed Builder

### ISSUE THREAD

**Issue by kzndotsh** [allthingslinux/tux#29]
https://discordpy.readthedocs.io/en/stable/api.html?highlight=embed#discord.Embed

**Comment by kzndotsh** [comment]
https://github.com/Rapptz/discord.py/blob/master/discord/embeds.py

**Comment by its-Lyn** [comment]
Started work on it in branch EmbedUtils

**Comment by kzndotsh** [comment]
Just posting more embed util references as I find them: https://github.com/Column01/Discord-Moderation-Bot/blob/master/helpers/embed_builder.py
