### ISSUE TITLE
Fun 8ball can be used to bypass filtered words

### ISSUE THREAD

**Issue by koknese** [allthingslinux/tux#342]

**Comment by kzndotsh** [comment]
Not possible.

**Comment by koknese** [comment]
> Not possible.

![image](https://github.com/user-attachments/assets/5f5ae3cb-9aa6-4fb0-81eb-8732a179964c)
Very much is.

**Comment by kzndotsh** [comment]
I meant not possible to fix*

**Comment by koknese** [comment]
> I meant not possible to fix*

It could be, for example, by adding an if statement that has regex for multitude of banned words and then throwing an error at the user and phoning home to the mods.

**Comment by rm-rf-tux** [comment]
How is "request shouldn't contain these words" not implementable?
Just copy the Discord blacklist into a Regex or hashmap (whichever is faster depending on the number of words) and make Tux check for that.
