### ISSUE TITLE
$av command makes gifs into a static image

### ISSUE THREAD

**Issue by aegnx** [allthingslinux/tux#374]
the ``$av`` command responds with the first frame of a gif as an image, a fix could be getting the gif link.
![Screenshot from 2024-08-05 00-23-51](https://github.com/user-attachments/assets/03b241cc-5ef5-4f25-a274-45016fbc470e)

**Comment by Atmois** [comment]
Should be fixed by https://github.com/allthingslinux/tux/pull/383
