### ISSUE TITLE
Accept repo content reports

### ISSUE THREAD

**Issue by nomnomshark41** [allthingslinux/tux#497]
![image](https://github.com/user-attachments/assets/312931d0-c16a-4213-9e30-ce0393e0f473)
to have the 100% community standart admins need to enable accepts content report from collaborators and prior

**Comment by kzndotsh** [comment]
![image](https://github.com/user-attachments/assets/2fc6564b-150e-4f13-bfbd-9792639d11d5)

**Comment by kzndotsh** [comment]
This appears to already be set?

**Comment by nomnomshark41** [comment]
can you try make it only prior contributors and collaborators @kzndotsh

**Comment by kzndotsh** [comment]
> can you try make it only prior contributors and collaborators @kzndotsh

why though? shouldnt anyone be allowed to?

**Comment by nomnomshark41** [comment]
it's the default thing and https://github.com/orgs/community/discussions/59546
> > can you try make it only prior contributors and collaborators @kzndotsh
> 
> why though? shouldnt anyone be allowed to?

**Comment by kzndotsh** [comment]
Done
