### ISSUE TITLE
on_ready()

### ISSUE THREAD

**Issue by kzndotsh** [allthingslinux/tux#55]
https://discordpy.readthedocs.io/en/stable/api.html#discord.on_ready

**Comment by kzndotsh** [comment]
other thoughts - if we abstract the sync/clear commands from main.py - how do we sync commands on the starting of the bot? do we execute a sync in the on ready event? or...

**Comment by kzndotsh** [comment]
further thoughts - because we are using a cog loader utility, maybe the first sync should take place here instead or fire off something else?

**Comment by kzndotsh** [comment]
by using the cog loader, does that in turn automatically sync the command tree due to the clear/sync commands being loaded?

**Comment by kzndotsh** [comment]
https://github.com/Rapptz/discord.py/discussions/8170

**Comment by jwe66** [comment]
```python
async def change_activity():
    while True:
        activities = [
            discord.Game("ur mom"),
            discord.Streaming(name="fortnite gamer hourz", url="http://twitch.tv/urmom"),
            discord.Activity(type=discord.ActivityType.listening, name="Why does it hurt when I pee? by Frank Zappa"),
            discord.Activity(type=discord.ActivityType.watching, name="Harry Potter and The Sorcerers Stone"),
        ]

        for activity in activities:
            await client.change_presence(activity=activity)
            await asyncio.sleep(300)

async def on_ready():
    asyncio.create_task(change_activity())
```

that will get scheduled on its own thread, so we are officially multithreaded bingus!!
