### ISSUE TITLE
[FEATURE] - Levels Rework

### ISSUE THREAD

**Issue by redgrxve0001** [allthingslinux/tux#562]
**LEVEL REWORK:**

The leveling system feels tedious and monotonous, with no real sense of reward. Here is my suggestion for a rework wich is designed to release more dopamine:

**SYSTEM ONE: _PRESTIGE_**

You will have a leveling cap, with 3 Prestiges. You can hit a maximum level (Such as 50) and then risk your whole level to go again and start from 0, with a fancy badge showing your prestige level and no perms however you can keep leveling back up but slightly higher for more perms. Here is my suggested layout:

**PRESTIGE 0** - Level 25
You get basic perms, and by level 25 you will have GIF perms and reaction perms

**PRESTIGE _1_** - Level 50
You will get Attachment perms, access to more channels (spaced out between levels) and the same perms as upto Level 25

**PRESTIGE _2_** - Level 75
You will get access to audit channels, and color roles

**PRESTIGE _3_** - Level **100**
You get all NON MODERATOR Perms along with a special role for being maximum level once you hit 100. You also will no longer need to Prestige.

Of course this can and should be changed as necessary.

          Love - ira/toxicbeings

**Comment by FluxC0** [comment]
i feel like this takes away too much from people. especially audits?

**Comment by Atmois** [comment]
I dont think this is a good idea, removing audit from everyone removes our transparancy and colour roles are for everyone to allow them to express themsevelvs freely. Also prestige just adds an uneccesary complication.

**Comment by rm-rf-tux** [comment]
Hell nah, moderation *must be transparent*. It's in the Code of Conduct. Wanting to be able to moderate without most of the community knowing what you're doing is quite suspicious.

**Comment by Atmois** [comment]
Closing this, if you wish to further discuss this idea please send it into #557
