### ISSUE TITLE
[FEATURE] - make a board of shame

### ISSUE THREAD

**Issue by GBX9570** [allthingslinux/tux#570]
## Is your feature request related to a problem? Please describe
no, it is not

## Describe the solution you'd like
Make a 'Board of Shame', like the starboard, except its anti-stars

## Describe alternatives you've considered
N/A

## Additional Context
If you see something thats so bad it deserves to be pinned on a board thats like 'how dare you post this' you can put it on the Board of Shame

**Comment by wlinator** [comment]
This is already possible. The term "starboard" is never used in the target channel so you can simply create a `#wall-of-shame` channel and load a starboard there with a custom "negative star" emoji.

```
$starboard setup #wall-of-shame <emoji> <threshold>
```
