### ISSUE TITLE
Move conversation command

### ISSUE THREAD

**Issue by tyract** [allthingslinux/tux#572]
there have been a lot of new channels/threads recently, and that caused some of them to become off topic, which isn't good. what would help is a command that notifies the users to switch channels.

a nice example is the bot from the r/unixporn team, rob. it has the ```move``` command implemented, and it helps a lot.
what is does is sends 2 embeds, in the target channel where the conversation needs to be moved to and the channel with the off-topic discussion.

just saying "please move this conversation elsewhere" might not always be clear, and chances are mods aren't gonna check if there's a random off-topic conversation in a different channel/thread.

------

what i'm referring to:

![Screenshot 2024-09-26 080830](https://github.com/user-attachments/assets/5d029f9a-f796-46c2-8dbf-065569ceb58d) - source channel
![Screenshot 2024-09-26 081453](https://github.com/user-attachments/assets/d69fb309-36a4-42bc-a130-db717412043d) - target channel

i hope i did a good job at trying to explain ;)

**Comment by rm-rf-tux** [comment]
Might not be possible due to API limitations but it would be cool to be able to move the last N messages of participants automatically
Each participant would need to agree to a move request though

**Comment by tyract** [comment]
messages, by themselves aren't moved, it's only a command for the bot to send 2 messages, 1 in the source channel and 1 in the target channel.

**Comment by rm-rf-tux** [comment]
Yeah I understand that was the point of the original issue, but I have noticed asking to move a discussion usually kills it, and I think we need a way to mitigate this
