### ISSUE TITLE
[BUG] - tux has been calling for a week..

### ISSUE THREAD

**Issue by fs2f** [allthingslinux/tux#635]
## Describe the Bug

the status of the bot hasn't changed in a week! free him from his misery

## To Reproduce

open discord, go to server, see tux's profile.

## Expected Behavior

tux doing other things that are more important than calling.. them fees must be high

## Environment (please complete the following information)

doesn't matter in this context, multiple users have reported it

## Additional Context

please free him asap..

**Comment by rm-rf-tux** [comment]
Tux is constantly making business deals to achieve Linux supremacy.

**Comment by fs2f** [comment]
good point.. however doesn't he deserve a break for his hard work

**Comment by kzndotsh** [comment]
Tux has been freed from his cubicle.
